config/routes.rb
Rails.application.routes.draw do
  
  root "static_pages#home"
  get 'static_pages/contact'

  resources :categories, shallow: true do
    resources :videos
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :videos
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    
    def new
        @category=Category.new
    end
    
    def create
        @category=Category.new(category_params)
        if @category.save
            redirect_to categories_path
        else
            render 'new'
        end
    end
    
    def show
        @category=Category.find(params[:id])
       
    end
    
    
    def index
        @category=Category.all
    end
    
    def edit
        @category=Category.find(params[:id])
    end
    
    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            redirect_to categories_path
        else
            render 'edit'
        end
    end
    
    def destroy
    end
    
    private
     def category_params
         params.require(:category).permit(:title, :contents)
     end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def contact
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
    
    def new
        @video= Video.new
    end
    
    def create
        @category = Category.find(params[:category_id])
        @category.videos.create(video_params)
         redirect_to categories_path(@category)
    end
    
    
    
    def show
        @video=Video.find(params[:id])
        @category= Category.find(params[:id])
    end
    
    def index
        @video=Video.all
    end
    
    def edit
    end
    
    def update
    end
    
    def destroy
    end
    
    private
     def video_params
         params.require(:video).permit(:title, :contents)
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
  def full_title(page_title)
    base_title = "Aesculapius App"
    if page_title.empty?
      base_title
    else
      "#{base_title}| #{page_title}"
    end
  end


end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/categories/edit.html.erb
<%= provide(:title, "Videos Category") %>

<%= render "static_pages/menu_bar" %>
<div class="container">
    <h2>Videos Category edit</h2>
    
        <div class= "row">
            <div class= "col-md-6 col-md-offset-3">
                
                <%= form_for (@category) do |f| %>
                    <%= f.label :title %>
                    <%= f.text_field :title%>
                    
                    <%= f.label :contents %>
                    <%= f.text_area :contents %>
                    
                    <%= f.submit "Create Videos Category" , class: "btn btn-primary" %>
                <%end%>   
                    
                    
            </div>
            
        
        </div>
    
</div>

app/views/categories/index.html.erb
<%= provide(:title,"Videos Caregory")%>

<%= render "static_pages/menu_bar" %>
<div class= "container">
<ol class="breadcrumb">
	<li><%= link_to "category", categories_path%></li>
	
</ol>
</div>

<div class="container">
<div class="category">
    <h2>Category</h2>
    <div class= "jumbotron">
     <ol class="list">
        <% @category.each do |category| %>
        <li>
        <%= link_to category.title, category_path(category), class: "title"%>
            <ul class="remarks">
                <li><%= category.contents %></li>
            </ul>
        </li>
        
        <% end %>
     </ol>
    </div>
</div>
</div>

app/views/categories/new.html.erb
<%= provide(:title, "Videos Category") %>

<%= render "static_pages/menu_bar" %>
<div class="container">
    <h2>Videos Category</h2>
    
        <div class= "row">
            <div class= "col-md-6 col-md-offset-3">
                
                <%= form_for (@category) do |f| %>
                    <%= f.label :title %>
                    <%= f.text_field :title%>
                    
                    <%= f.label :contents %>
                    <%= f.text_area :contents %>
                    
                    <%= f.submit "Create Videos Category" , class: "btn btn-primary" %>
                <%end%>   
                    
                    
            </div>
            
        
        </div>
    
</div>

app/views/categories/show.html.erb
<%= provide(:title,"Videos Caregory")%>

<%= render "static_pages/menu_bar" %>
<div class= "container">
<ol class="breadcrumb">
	<li><%= link_to "category", categories_path%></li>
	<li><%= link_to "video", category_videos_path(@category) %></li>
</ol>

<div class="category">
    <h2><%=@category.title %></h2>
     <div class= "jumbotron">
         <div class="item">Video teaching materials</div>
        <ol class= "list">
            <% @category.videos.each do |video| %>
            <li>
                <%= video.title %>
                <%= link_to "Watch", video_path, class: "btn btn-primary btn-xs" %>
                    <ul class="remarks">
                        <li><%= video.contents %></li>
                    </ul>
            </li>
            <% end %>
        </ol>
     </div>
</div>
<div clss = "btn">
    <%= link_to "New Video Registration", new_category_video_path(@category), class: "btn btn-primary" %>
</div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
    <div class= "container">
        <h2> Aesculapius</h2>
            
    </div>
    
</header>

app/views/layouts/_shiv.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AesculapiusApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render "layouts/shiv" %>
  </head>

  <body>
    
    <%= render "layouts/header" %>
    <div class="container">
    <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/static_pages/_menu_bar.html.erb
<menu_bar class= "menu_bar ">
    <div class="container">
    <nav>
        <ul class="nav nav-pills">
            <li><%=link_to "Home",root_path %></li>
            <li><%=link_to "Video teaching materials",categories_path %></li>
            <li><%=link_to "Material purchase","#"%></li>
        </ul>
    </nav>
    </div>
</menu_bar>

app/views/static_pages/home.html.erb
<div class="container">
<div>
<%= render "static_pages/menu_bar" %>
</div>
<div class="container">
    <div class="scroll-area">
    
        <div class="box box__bg_photo">仲間を、日本を、世界を成功に導く会社
            <h1>「大 成 幸 株式会社」</h1>
        </div>
    
        <div class="box box__bg_gray">
            <p>理念</p>
        </div>
        <div class="box box__bg_black">
            <p>思い、志</p>
        </div>
    
    </div>
</div>
</div>

app/views/videos/_breadcrumbs.html.erb
<div class= "container">
<ol class="breadcrumb">
	<li><%= link_to "category", categories_path%></li>
	<li><%= link_to "video", category_videos_path(@category) %></li>
	<li class="active"><%= @video.title %></li>
</ol>
</div>

app/views/videos/index.html.erb
<% provide(:title, "Video teaching materials") %>

<%= render "static_pages/menu_bar" %>
<div class= "container">
<ol class="breadcrumb">
	<li><%= link_to "category", categories_path%></li>
</ol>
</div>

<div class="container">
    <h2>Video teaching materials</h2>
</div>

app/views/videos/new.html.erb
<% provide(:title, "Videos new") %>

<%= render "static_pages/menu_bar" %>
<div class="container">
    <h2>Videos </h2>
    
        <div class= "row">
            <div class= "col-md-6 col-md-offset-3">
                <%= form_for(@video,url:category_videos_path) do |f| %>
                    <%= f.label :title %>
                    <%= f.text_field :title %>
    
                    <%= f.label :contents %>
                    <%= f.text_area :contents %>
    
                    <%= f.submit :"Create Video", class: "btn btn-primary" %>
                <%end%>
                
            </div>
        </div>
</div>

app/views/videos/show.html.erb
<% provide(:title, "Video teaching materials") %>

<%= render "static_pages/menu_bar" %>
<%= render "videos/breadcrumbs" %>

<div class= "container">
<h2><%= @video.title%></h2>
</div>